apiVersion: v1
kind: Service
metadata:
  name: tb-mqtt-loadbalancer-external
  namespace: thingsboard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-mqtt-transport
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
      protocol: TCP
    - port: 8883
      targetPort: 8883
      name: mqtts
---
apiVersion: v1
kind: Service
metadata:
  name: tb-coap-loadbalancer-external
  namespace: thingsboard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-coap-transport
  ports:
    - port: 5683
      targetPort: 5683
      name: coap
      protocol: UDP
---
