apiVersion: v1
kind: Service
metadata:
  name: tb-mqtt-loadbalancer
  namespace: thingsboard
  annotations:
    networking.gke.io/managed-certificates: managed-cert
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-node
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
    - port: 8883
      targetPort: 8883
      name: mqtts